name: Tally
author: Myyk
description: Tally votes on PR
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the repository in which to tally votes.'
  comment-id:
    description: Comment id of comment containing votes.
    required: true
outputs:
  for:
    description: The number for the change.
  against:
    description: The number against the change.
runs:
  using: node12
  main: index.js
