name: Update npm Dependencies after Dependabot package upgrade
on:
  pull_request:
    branches:
    - dependabot/npm_and_yarn/**

permissions:
  contents: write

jobs:
  run:
    name: Run npm install
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install
      - run: |
          GITHUB_TOKEN=${{ github.token }} yarn run all

      - name: Generate Commit Message
        id: generate_commit_message
        # eg: ⬆️ Bump @types/node-16.9.4 npm packages 
        run: |
          branch=${GITHUB_REF#refs/heads/}
          # add `[dependabot skip]` prefix so Dependabot force pushes any rebases over our changes triggering the action again
          commit_message="Bump ${branch//dependabot\/npm_and_yarn\// } npm packages%0A%0A[dependabot skip]"
          echo ::set-output name=commit_message::$commit_message

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: ${{ steps.generate_commit_message.outputs.commit_message }}

