name: 'ci'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-ci: # make sure build/ci work properly
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/reusable_ci.yml
    secrets: inherit

