name: 'ci'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - '**'
      - '!dependabot/npm_and_yarn/**'
  push:
    branches:
      - main
      - 'releases/*'
      - '!dependabot/npm_and_yarn/**'

jobs:
  run-ci: # make sure build/ci work properly
    uses: ./.github/workflows/reusable_ci.yml
    secrets: inherit

