name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          GITHUB_TOKEN=${{ github.token }} yarn run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repository: myyk/git-democracy
          payloadAction: opened # this is overriden so that this can work when triggered by other PRs for their CIs
          issueNumber: 71 # this is a permenant PR left for testing
