name: 'ci'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-ci: # make sure build/ci work properly
    uses: ./.github/workflows/reusable_ci.yml
    secrets: inherit

