# When Dependabot updates dependency, this workflow synchronize the change
# to the /dist dir to let users enjoy new feature without manual sync.
name: Update the dist dir
on:
  pull_request_target:
    types:
      - labeled # for initial execution
      - synchronize # to support `@dependabot recreate` command

permissions:
  contents: write
  pull-requests: write

jobs:
  run-ncc:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }} # Replace github.token with PAT (personal access token) if you need to trigger a new workflow. https://git.io/JcHD9
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # It is not suggested to cache for the pull_request_target event
          # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
      - name: Install dependencies
        run: yarn install --immutable
      - name: Update the dist directory
        run: |
          INPUT_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} yarn run all
          if [[ $(git status -s -- dist | wc -l) -gt 0 ]]; then
            git add dist
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "chore: sync the dependency update to the /dist dir"
            git push origin HEAD
          fi
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
